Fix -Werror=shadow in basesh.cxx
sw/source/uibase/shells/basesh.cxx:
 In member function ‘void SwBaseShell::ExecUndo(SfxRequest&)’:
sw/source/uibase/shells/basesh.cxx:564:29: error: declaration
 of ‘rView’ shadows a member of ‘SwBaseShell’ [-Werror=shadow]
  564 |                     SwView& rView = rWrtShell.GetView();
      |                             ^~~~~
In file included from sw/source/uibase/shells/basesh.cxx:63:
sw/source/uibase/inc/basesh.hxx:41:18: note: shadowed declaration
 is here
   41 |     SwView      &rView;
      |                  ^~~~~

Since c72e500ccaf0ce2261c5233b80fba9342778f810.

Change-Id: I5fda3ad4805dc59a9e0e01dd262c09952a2bc97e
Reviewed-on: https://gerrit.libreoffice.org/c/core/+/125077
Tested-by: Jenkins CollaboraOffice <jenkinscollaboraoffice@gmail.com>
Reviewed-by: Aron Budea <aron.budea@collabora.com>